/**
 * Content for the policy and information pages.
 *
 * Written to describe what this application actually does — the data it stores,
 * the cookies it sets, the third parties it sends data to — rather than generic
 * boilerplate. Keeping it here means one place to update when behaviour changes.
 *
 * This is a plain-English description of current behaviour, not legal advice.
 * Have a qualified lawyer review it before relying on it, especially for the
 * age-restricted categories and for handling identity documents.
 */

export const SITE_NAME = "Profinr";
export const CONTACT_EMAIL = "support@profinr.com";
export const LAST_UPDATED = "16 August 2026";

export type LegalSection = {
  heading: string;
  paragraphs?: string[];
  bullets?: string[];
};

export const privacySections: LegalSection[] = [
  {
    heading: "What this policy covers",
    paragraphs: [
      `${SITE_NAME} is a directory where visitors search for service providers and business owners publish a profile. This policy explains what we collect, why, and who it is shared with.`,
      "It applies to this website and the API behind it. It does not cover the providers listed here — once you contact a provider directly, their own handling of your information is between you and them."
    ]
  },
  {
    heading: "Information you give us",
    bullets: [
      "Account details: your name, email address and a password. Passwords are stored only as a bcrypt hash and cannot be read back by us or anyone else.",
      "Business profile content, if you register as an owner: business name, description, services, pricing notes, availability, address, phone, WhatsApp number and website.",
      "Media you upload: cover images, gallery photos and video.",
      "Enquiries you send to a provider, including the phone number, service and message you enter.",
      "Identity and age-verification documents, where a category requires them."
    ]
  },
  {
    heading: "Information collected automatically",
    bullets: [
      "Profile view counts and interaction events (for example, whether a call or WhatsApp button was used), which owners see as aggregate numbers on their dashboard.",
      "Your IP address, used to apply rate limits that protect the site from abuse such as password guessing. It is held only for the length of the rate-limit window.",
      "Standard server logs generated by our hosting provider."
    ]
  },
  {
    heading: "Cookies",
    paragraphs: [
      "We do not use advertising or third-party tracking cookies. The cookies we set are functional only:"
    ],
    bullets: [
      "session_token and admin_token — keep you signed in. They are httpOnly, so scripts on the page cannot read them, marked Secure, and expire after 8 hours.",
      "signup_intent — a short-lived cookie that remembers you were part-way through adding a business profile, so the sign-up flow can send you back to the right place. It expires in 15 minutes."
    ]
  },
  {
    heading: "Identity and age-verification documents",
    paragraphs: [
      "Some categories are age-restricted and require a government ID or an age-verification selfie before a profile can be published.",
      "These documents are handled differently from ordinary images. They are stored in a private, access-controlled bucket separate from public media, are never served from a public URL, and can only be retrieved by an administrator through an authenticated request. They are used solely to confirm identity and age, and are never shown on a public profile."
    ]
  },
  {
    heading: "Who we share information with",
    paragraphs: ["We do not sell your information. We share it only with the services needed to run the site:"],
    bullets: [
      "Supabase — hosts our database and the private storage used for verification documents.",
      "Hostinger — hosts the website and the API, and stores public gallery images.",
      "Our email provider — delivers verification and password-reset emails.",
      "Razorpay — processes payments, where online payment is enabled. Card details are handled by Razorpay and never reach our servers.",
      "Anything you choose to publish on a business profile is public by design, including to search engines."
    ]
  },
  {
    heading: "How long we keep it",
    bullets: [
      "Account and profile data: until you ask us to delete the account.",
      "Verification documents: while the profile is active, and removed when the account is deleted.",
      "Enquiries: retained so the provider and you both have a record of the exchange.",
      "Rate-limit records: minutes, then discarded."
    ]
  },
  {
    heading: "Your choices",
    paragraphs: [
      `You can ask us for a copy of your data, ask us to correct it, or ask us to delete your account and everything attached to it. Email ${CONTACT_EMAIL} from the address on the account and we will action it.`,
      "Deleting your account removes your profile from the directory. Search engines may keep a cached copy for a while after that, which is outside our control."
    ]
  },
  {
    heading: "Security",
    paragraphs: [
      "Traffic is served over HTTPS with HSTS. Passwords are hashed with bcrypt. Sessions are httpOnly cookies rather than tokens readable by page scripts. Administrative areas require an administrator account, and verification documents sit behind private storage.",
      "No system is perfectly secure, but if you believe you have found a vulnerability we would genuinely like to hear about it — email us and we will look at it promptly."
    ]
  },
  {
    heading: "Children",
    paragraphs: [
      "This site is not intended for anyone under 18. Age-restricted categories require age confirmation and, where applicable, verification documents. If you believe a minor has created an account, contact us and we will remove it."
    ]
  }
];

export const termsSections: LegalSection[] = [
  {
    heading: "What Profinr is",
    paragraphs: [
      `${SITE_NAME} is a directory. We list service providers and give visitors a way to compare and contact them. We are not a party to any arrangement you make with a provider, we do not supply the services listed, and we do not employ, endorse or supervise the people or businesses on this site.`
    ]
  },
  {
    heading: "Verification means a specific thing",
    paragraphs: [
      "A verification badge means a profile completed the relevant review step — for example, that a submitted document was checked. It is not a guarantee of quality, licensing, insurance, or that a provider will do what they promise.",
      "You are responsible for your own checks before hiring anyone: qualifications, licences, references, pricing and terms. Treat the directory as a starting point, not a substitute for judgement."
    ]
  },
  {
    heading: "Your account",
    bullets: [
      "Give accurate details and keep your password to yourself. You are responsible for activity under your account.",
      "One business profile per owner account.",
      "Confirm your email before publishing a profile or posting reviews.",
      "We may suspend accounts that break these terms or the law."
    ]
  },
  {
    heading: "Rules for business owners",
    bullets: [
      "List only services you are legally allowed to provide, and hold the licences your work requires.",
      "Keep pricing, availability and contact details accurate and current.",
      "Upload only media you own or have permission to use.",
      "No misleading claims, fake reviews, or impersonating another business.",
      "Profiles are published only after review, and we may decline or remove a listing at our discretion."
    ]
  },
  {
    heading: "Age-restricted categories",
    paragraphs: [
      "Some categories are restricted to adults and require age confirmation to view. Providers in these categories may be required to supply identity and age verification before publication.",
      "These listings are for lawful companionship and related services only. Advertising anything illegal is prohibited, will be removed, and may be reported to the authorities."
    ]
  },
  {
    heading: "Reviews and content you post",
    paragraphs: [
      "Reviews should reflect genuine experience. We remove content that is abusive, defamatory, discriminatory, or posted to manipulate a provider's standing.",
      "You keep ownership of what you post, and you grant us permission to display it on the site and in search results."
    ]
  },
  {
    heading: "Payments",
    paragraphs: [
      "Featured placement and wallet top-ups, where offered, are paid in advance. Payments are handled by our payment processor. Amounts already spent on a placement that has run are not refundable; if a placement has not started, contact us and we will sort it out."
    ]
  },
  {
    heading: "Limits on our liability",
    paragraphs: [
      "The site is provided as it is. To the extent the law allows, we are not liable for loss arising from your dealings with a provider, from information published by a provider, or from the site being unavailable.",
      "Nothing here limits liability that cannot be limited by law."
    ]
  },
  {
    heading: "Changes",
    paragraphs: [
      "We may update these terms as the service changes. The date at the top of this page shows the last revision, and continuing to use the site means you accept the current version."
    ]
  }
];

export const disclaimerSections: LegalSection[] = [
  {
    heading: "We do not provide the services listed",
    paragraphs: [
      `${SITE_NAME} publishes listings supplied by third-party businesses. We do not perform, supervise or guarantee any service you find here, and we are not an agency, employer or broker for the providers listed.`
    ]
  },
  {
    heading: "Listing information comes from providers",
    paragraphs: [
      "Descriptions, prices, availability, qualifications and photographs are supplied by the provider. We review submissions before publication, but we cannot independently confirm every claim. Details change and may be out of date.",
      "Confirm anything that matters — price, licence, insurance, availability — directly with the provider before you commit."
    ]
  },
  {
    heading: "Reviews and ratings",
    paragraphs: [
      "Ratings reflect opinions of individual users, not our assessment. We remove reviews we find to be fake or abusive, but a rating should be read as one signal among several."
    ]
  },
  {
    heading: "External links",
    paragraphs: [
      "Profiles may link to provider websites, WhatsApp or social accounts. We do not control those destinations and are not responsible for their content or their handling of your data."
    ]
  },
  {
    heading: "Your safety",
    paragraphs: [
      "Use ordinary caution when arranging any service with someone you found online. Meet in appropriate settings, agree terms in writing where the amount matters, and avoid unusual payment arrangements. If a listing looks fraudulent or unsafe, report it to us and we will investigate."
    ]
  }
];
